{
    "openapi": "3.0.2",
    "info": {
      "title": "UntukKita API - COVID Sidoarjo Datalake",
      "description": "UntukKita API",
      "termsOfService": "https://api.untukkita.my.id/term-of-service",
      "contact": {
        "name": "Rengga Prakoso Nugroho",
        "url": "https://github.com/untukkita-id",
        "email": "rengga.prakoso.2001216@students.um.ac.id"
      },
      "license": {
        "name": "Apache License 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0"
      },
      "version": "1.0.0"
    },
    "servers": [
      {
        "url": "https://virtserver.swaggerhub.com/vzrenggamani/untukkita-covid-api/1.0.0",
        "description": "SwaggerHub API Auto Mocking"
      },
      {
        "url": "https://api.untukkita.my.id/covid/sda"
      }
    ],
    "security": [
      {}
    ],
    "paths": {
      "/": {
        "get": {
          "tags": [
            "Public Endpoint"
          ],
          "summary": "Get API Status",
          "description": "Get API Status",
          "operationId": "getStatus",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/inline_response_200"
                  }
                }
              }
            }
          }
        }
      },
      "/fasilitaskesehatan": {
        "get": {
          "tags": [
            "Public Endpoint"
          ],
          "summary": "Get Fasilitas Kesehatan",
          "description": "Get Fasilitas Kesehatan",
          "operationId": "getFasilitasKesehatan",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/FasilitasKesehatan"
                  }
                }
              }
            },
            "404": {
              "description": "Not Found",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          }
        }
      },
      "/kasus": {
        "get": {
          "tags": [
            "Public Endpoint"
          ],
          "summary": "Get Kasus",
          "description": "Get Kasus",
          "operationId": "getKasus",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/StatistikCovid"
                  }
                }
              }
            }
          }
        }
      },
      "/vaksinasi": {
        "get": {
          "tags": [
            "Public Endpoint"
          ],
          "summary": "Get Vaksinasi",
          "description": "Get Vaksinasi",
          "operationId": "getVaksinasi",
          "responses": {
            "200": {
              "description": "Success",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DataVaksinasi"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "FasilitasKesehatan": {
          "required": [
            "alamat",
            "id",
            "jenis",
            "kontak",
            "nama_faskes",
            "sosialmedia"
          ],
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "format": "int64"
            },
            "nama_faskes": {
              "type": "string"
            },
            "jenis": {
              "type": "string"
            },
            "kontak": {
              "type": "string"
            },
            "alamat": {
              "type": "string"
            },
            "sosialmedia": {
              "type": "string"
            },
            "verifikasi": {
              "type": "string"
            },
            "sumberdata": {
              "type": "string"
            }
          },
          "example": {
            "id": 1,
            "nama_faskes": "RSU Dr. Soetomo",
            "jenis": "Rumah Sakit Umum",
            "kontak": "0812-1234-1234",
            "alamat": "Jl. Dr. Soetomo No. 1",
            "sosialmedia": "https://www.facebook.com/drsoetomo",
            "verifikasi": "Verifikasi",
            "sumberdata": "Sumber Data"
          }
        },
        "DataVaksinasi": {
          "required": [
            "cakupan",
            "id",
            "jenis",
            "kuota",
            "lokasi",
            "narahubung",
            "pelaksanaan",
            "penyelenggara",
            "sosialmedia",
            "verifikasi"
          ],
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "format": "int64"
            },
            "penyelenggara": {
              "type": "string"
            },
            "kuota": {
              "type": "integer"
            },
            "jenis": {
              "type": "string"
            },
            "cakupan": {
              "type": "string"
            },
            "lokasi": {
              "type": "string"
            },
            "sosialmedia": {
              "type": "string"
            },
            "narahubung": {
              "type": "string"
            },
            "pelaksanaan": {
              "type": "string",
              "format": "date"
            },
            "verifikasi": {
              "type": "boolean"
            }
          },
          "example": {
            "id": 1,
            "penyelenggara": "RSU Dr. Soetomo",
            "kuota": 100,
            "jenis": "Sinovac",
            "cakupan": "Umum",
            "lokasi": "Jl. Dr. Soetomo No. 1",
            "sosialmedia": "https://www.facebook.com/drsoetomo",
            "narahubung": "0812-1234-1234",
            "pelaksanaan": "2020-01-01",
            "verifikasi": true
          }
        },
        "StatistikCovid": {
          "required": [
            "meninggal",
            "positif",
            "sembuh",
            "updateTerakhir"
          ],
          "type": "object",
          "properties": {
            "positif": {
              "type": "integer",
              "format": "int64"
            },
            "sembuh": {
              "type": "integer",
              "format": "int64"
            },
            "meninggal": {
              "type": "integer",
              "format": "int64"
            },
            "updateTerakhir": {
              "type": "string",
              "format": "date"
            }
          },
          "example": {
            "positif": 100,
            "sembuh": 10,
            "meninggal": 1,
            "updateTerakhir": "2020-04-01"
          }
        },
        "ErrorResponse": {
          "required": [
            "message",
            "status",
            "timestamp",
            "type"
          ],
          "type": "object",
          "properties": {
            "status": {
              "type": "integer",
              "description": "API Status"
            },
            "type": {
              "type": "string",
              "description": "API Type"
            },
            "message": {
              "type": "string",
              "description": "API Message"
            },
            "timestamp": {
              "type": "string",
              "description": "API Timestamp"
            }
          },
          "example": {
            "status": 404,
            "type": "RoutesNotFound",
            "message": "Not Found",
            "timestamp": "2020-04-01"
          }
        },
        "inline_response_200": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "description": "API Status"
            },
            "version": {
              "type": "string",
              "description": "API Version"
            },
            "uptime": {
              "type": "string",
              "description": "API Uptime"
            },
            "timestamp": {
              "type": "string",
              "description": "API Timestamp"
            },
            "message": {
              "type": "string",
              "description": "API Message"
            }
          }
        }
      }
    }
  }